### ISSUE TITLE
[Bug]: app_url passed from dsn shouldn't contain the DSN-only properties

### ISSUE THREAD

**Issue by dkarlovi** [Unleash/unleash-client-symfony#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The DSN-only properties introduced in #57 shouldn't be passed into `app_url`.

### To reproduce

1. configure like so

```yaml
unleash_client:
    dsn: https://gitlab.com/api/v4/feature_flags/unleash/12345678?instance_id=ABCDEFGH&app_name=myCoolApp
```

2. run `bin/console unleash:test foo -f -vv`
3. notice it's using the full DSN to talk to GL while it should only use `https://gitlab.com/api/v4/feature_flags/unleash/12345678`

### Version

0.11

### Expected behavior

Pass the app_url without DSN-only properties.

**Comment by RikudouSage** [comment]
I'm failing to reproduce this, I've set the dsn to `https://gitlab.com/api/v4/feature_flags/unleash/12345678?instance_id=ABCDEFGH&app_name=myCoolApp` and it correctly parses the DSN and does not include the instance_id and app_name.

Can you provide a simple reproducer?

**Comment by dkarlovi** [comment]
You're right, I can't reproduce it outside my app, that's really odd. :thinking: Closing, sorry for the noise. :+1:

**Comment by RikudouSage** [comment]
Any chance your app is open source? I'd love to take a look at this, I'm very curious about the cause of the error.
