### ISSUE TITLE
[Bug]: Example DSN in documentation is invalid

### ISSUE THREAD

**Issue by benr77** [Unleash/unleash-client-symfony#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the documentation, the DSN is specified as follows

```yaml
http://localhost:4242/api&instance_id=myCoolApp-Server1&app_name=myCoolApp
```

However, this is invalid and will not parse. The `&instance_id` should be `?instance_id` as otherwise `parse_url` cannot extract a query string as there is no `?` character.

### To reproduce

For people who are taking the example config and substituting their own values one by one, this will lead to an error, which is not very clearly described.

### Version

v0.11.182

### Expected behavior

It should show a better error message explaining the DSN is invalid.

**Comment by andreas-unleash** [comment]
Hi @benr77 .  Thanks for catching!

**Comment by benr77** [comment]
See https://github.com/Unleash/unleash-client-symfony/pull/67
