### ISSUE TITLE
[Bug]: client is not marked lazy, tries to connect to the Unleash server when building Twig cache

### ISSUE THREAD

**Issue by dkarlovi** [Unleash/unleash-client-symfony#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See https://github.com/symfony/symfony/issues/53436 for all details

### To reproduce

Described in https://github.com/symfony/symfony/issues/53436

### Version

0.11.2

### Expected behavior

This happens when building the cache in a Docker environment which doesn't have access to the Unleash server (the location of the server is runtime, it's not available at buildtime).

Suggested fix is to mark the client as lazy like so:
https://symfony.com/doc/current/service_container/lazy_services.html#interface-proxifying

**Comment by RikudouSage** [comment]
Can you check out #71? I've made it both use a runtime class and lazy loadable using `ExtensionInterface` but I don't think either of that will solve your problem.

**Comment by dkarlovi** [comment]
@RikudouSage it works indeed.
