### ISSUE TITLE
[Discussion]: Unleash integration in a (potential) Symfony component

### ISSUE THREAD

**Issue by Jean-Beru** [Unleash/unleash-client-symfony#75]
As mentioned in this [comment](https://github.com/symfony/symfony/pull/53213#issuecomment-2052378466), a FeatureFlag component has been proposed to Symfony. Its goal is to propose a way to declare feature flags from different ways.

If accepted, it will be possible to implement an Unleash adapter for this component.

Maybe we can start a discussion here to see if this could give the same features and so reduce the workload on this bundle. WDYT ?

**Comment by RikudouSage** [comment]
Nice! I think I'll be writing an official adapter once some public api stabilizes.

I think I've generally chosen a good approach here when it comes to the code and service structure, feel free to get inspired.

**Comment by RikudouSage** [comment]
As for the points you raised: 

- if you decide to make caching part of the package, you should think of different types of cache, like standard short cache and stale cache for failures 
- aside from bootstrapping the component, there should be close to no exceptions thrown at runtime, this bundle (and underlying library) tries really hard to recover from any failure
- something like the cache specifier service from this bundle might be needed to modify the key based on app state

Though I'm not sure this is the way you'd want to go, simple interface with `isEnabled()` would IMO be better and caching would be the responsibility of the implementors.

IMO you should think about something akin to variants from Unleash, which basically makes it possible to return a payload along with your feature flags, which is very useful for A/B testing.

**Comment by Jean-Beru** [comment]
Thanks for your feedback!

> something like the cache specifier service from this bundle might be needed to modify the key based on app state

That's a tricky part when using a context for feature resolution. No context is supported for now in the component proposal but it could be more complex than https://github.com/Unleash/unleash-client-php/blob/7353c74e1efde40634379282711bdb224df9a857/src/Repository/DefaultUnleashProxyRepository.php#L86 since it could contain objects (ex: `Request`).

> Though I'm not sure this is the way you'd want to go, simple interface with isEnabled() would IMO be better and caching would be the responsibility of the implementors.
> IMO you should think about something akin to variants from Unleash, which basically makes it possible to return a payload along with your feature flags, which is very useful for A/B testing.

Sure. They are named `isEnabled(string $featureName, mixed $expectedValue = true): bool` and `getValue(string $featureName): mixed` for now. Note that the value is compared to an expected value to determine if the feature variant is enabled.

**Comment by RikudouSage** [comment]
Well, the proxy repository is used when you don't want to do local resolution but let Unleash server handle it, not relevant to the new component.

The [Symfony context](https://github.com/Unleash/unleash-client-symfony/blob/main/src/Context/SymfonyUnleashContext.php) would be more relevant. Though it still cannot return objects, only strings for custom properties.
